server:
  port: 8120 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: www.nacos-dev.com:8848 # nacos服务地址
        namespace: a4429396-1a75-4dc6-8c8c-874e08ec2fee

# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
alibaba:
  cloud:
    access-key: 1
    secret-key: 2
    # oss控制台: https://oss.console.aliyun.com
    # oss云存储的EndPoint（地域节点）
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketName: 3

