server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: www.nacos-dev.com:8848 # nacos服务地址
        namespace: a4429396-1a75-4dc6-8c8c-874e08ec2fee
  #spring:
  redis:
    host: www.redis-dev.com
    password: 1
    database: 7
    port: 6381

# spring cloud access&secret config
# 可以访问如下地址查看: https://usercenter.console.aliyun.com/#/manage/ak
alibaba:
  cloud:
    access-key: 2
    secret-key: 3
#阿里云短信
aliyun:
  sms:
    regionId: cn-hangzhou
    templateCode: 4
    signName: 5
